### ISSUE TITLE
implementation

### ISSUE THREAD

**Issue by dgcovell** [dphansti/CORAL#17]
I have been unable to get CORAL to work in a windows or linux application, and am seeking guidance. I have downloaded the CORAL-master utilities 
(ui.R, global.R, server.R, Coral.proj, README.md and the directories www, R and Data). Following the steps in global.R, the correct libraries have been loaded into R (3.3.2). Since I am attempting to implement in the R package on a windows and linux machine, the ‘data.tree’ package presented most of the problems. When the appropriate packages were installed, the library(‘data.tree’) finally worked for both machines. 
>install.packages("data.tree" , dependencies=T) did not pick up the needed packages, so each was done separately. Regardless, all the libraries could be loaded and the sourced *.R files yielded no errors.
However, in both the windows and linux machines 

> source(‘global.R’)  gives the same error

> rna_data     = paste(readLines("Data/RNAdata.txt"),collapse="\n")
Warning message:
In readLines("Data/RNAdata.txt") :
  incomplete final line found on 'Data/RNAdata.txt'

> rna_abs_data = paste(readLines("Data/RNAdata_pluripotent.txt"),collapse="\n")
Warning message:
In readLines("Data/RNAdata_pluripotent.txt") :
  incomplete final line found on 'Data/RNAdata_pluripotent.txt'

I inspected both files and added a \n to the final line, without success. 

Any suggestions would be most appreciated. 

I would also ask about the D3.js java script library. I have not encountered a java ‘hook’ in R. I have downloaded D3.js to the CORAL-master directory. 
Is there a pointer for that location that needs to be run within R?

Finally, I am looking forward to generating images using CORAL. Your ‘examples’ are quite impressive, however, a suite of sample scripts would be helpful (or a pdf writeup). If this information is available at http://phanstiel-lab.med.unc.edu/CORAL/ please direct me to where. So far I do not seem to have the capacity to implement anything. I would add the >source(‘./R/Test.R’), does not generate any of the output expected from this script.  

Thanks in advance for your help,

David Covell, Ph.D.
NIH-NCI

**Comment by dphansti** [comment]
Coral is a web app.  Just go to the website and use it directly there.  

http://phanstiel-lab.med.unc.edu/CORAL/

It was not designed to be downloaded and run locally.  But it should work just fine.  Just clone to you computer, open the project in R studio, and run the app.  I just tested a fresh install on OSX and it worked fine.

You can ignore those warning messages.

You should not have to download anything else.  d3.v3.min.js is included in the package.
