### ISSUE TITLE
web application error "disconnected from the server"

### ISSUE THREAD

**Issue by sharespoon** [dphansti/CORAL#18]
Hi, the graphs of Coral look nice and I would like to draw some kinome trees with it. I tried to use your web application http://phanstiel-lab.med.unc.edu/CORAL/. I first specify the "node color" with categorical input of 25 kinases. Before the graph is updated, the error shows up "disconnected from the server". How can I fix this? Thank you!

**Comment by mbergins** [comment]
This might be due to us recently needing run some updates on the server as I think this error message is typical for when shiny server is restarted. Everything should be back to normal and hopefully you didn't lose any work.
