### ISSUE TITLE
Error object 'controlLabel' not found

### ISSUE THREAD

**Issue by pramodkp** [dphansti/CORAL#19]
When i am running the app following error occuring :
> shiny::runApp()
Loading required package: shiny
Attaching package: ‘shinydashboard’
The following object is masked from ‘package:graphics’:
    box
Attaching package: ‘colourpicker’
The following object is masked from ‘package:shiny’:
    runExample
Attaching package: ‘DT’
The following objects are masked from ‘package:shiny’:
    dataTableOutput, renderDataTable
Attaching package: ‘jsonlite’
The following object is masked from ‘package:shiny’:
    validate
Listening on http://127.0.0.1:7122
Warning: Error in get: object 'controlLabel' not found
  93: get
  92: :::
  89: radioButtons_withHTML [R/radiobuttonswithimages.R#19]

**Comment by jeantravassos** [comment]
Hi, 
I am having exactly the same error. 
Could you manage to run it @pramodkp ?

Any tips about how to run the app properly?

Thanks

**Comment by cwenger** [comment]
Hi @pramodkp and @jeantravassos. This error is due to a shiny package update. It has been fixed with commit https://github.com/dphansti/CORAL/commit/685a839857e6ed23200c4ae5a93d58dda7ba3b18. Thanks for letting us know!
