### ISSUE TITLE
Missing Images in Repo

### ISSUE THREAD

**Issue by mbergins** [dphansti/CORAL#8]
I think the repo is missing a set of png's that are supposed to be in the www/images folder.

**Comment by anupshah14** [comment]
I had the same error message popped up while deploying the shinyapp. Could not find `images` folder under `www`.

```
Error in plot.new() : could not open file 'www/images/Erika.png'
Calls: runApp ... ..stacktraceon.. -> drawmypalettes -> plot -> plot.default -> plot.new
Execution halted
```

**Comment by armish** [comment]
Also had the same issue but I thought it was due to my setup.

**Comment by mbergins** [comment]
When I encountered this problem it had to do with the permissions set on the "www" folder, namely that the shinyapp user wasn't able to make "www/images" folder. We got around this by opening the permissions on www manually, but I can't remember the exact settings off the top of my head.

As far as I know Git can't retain the appropriate directory permissions to make this happen seamlessly.

**Comment by anupshah14** [comment]
Thanks for your advise. Assigning read and write permission to shiny user for `www` folder solved the issue.
